import type { EditorialStory } from "./editorial-types";
import { initiativeFeaturedImages, initiativeMedia } from "./initiative-media";

const images = {
  library: initiativeFeaturedImages["mini-library-mission-outreach"] ?? "/images/learning-event.jpg",
  campus: initiativeFeaturedImages["web3-on-campus"] ?? "/images/classroom-session.jpg",
  builders: initiativeFeaturedImages["builder-programs"] ?? "/images/group-discussion.jpg",
  community: "/images/community-gathering.jpg",
  learning: "/images/encyclopedia-cover.png",
  people: "/images/tita-arsh.png",
  event: "/images/wave3-cover.png",
  book: "/images/cook-cover.png",
};

type InitiativeInput = Pick<EditorialStory, "slug" | "title" | "category" | "summary" | "intro" | "heroImage" | "imageAlt"> & {
  why: string[];
  what: string[];
  impact: string[];
  bullets?: string[];
};

const initiativeRecords: InitiativeInput[] = [
  {
    slug: "mini-library-mission-outreach",
    title: "Mini-Library Mission & Outreach Program",
    category: "Community & Education",
    summary: "Bringing books, school supplies, educational resources, and learning opportunities to underserved communities.",
    intro: "The Mini-Library Mission & Outreach Program is Cryptita Plays’ flagship social-impact initiative, connecting access to learning resources with community outreach.",
    heroImage: images.library,
    imageAlt: "A learning event with community participants",
    why: ["Access to books and learning materials can help create more opportunities for children and students. The program brings those resources closer to communities that have fewer of them.", "The initiative pairs practical educational support with opportunities to learn and participate in community activities."],
    what: ["Missions and supported communities named in the current program notes include Murcia, Negros Occidental; Kabatuhan; Comota National High School in Agusan del Sur; and Marinduque.", "Activities may include mini-library resources, books, school supplies, educational sessions, and outreach. The long-term goal is to establish 10 mini-libraries nationwide."],
    impact: ["The stated long-term goal is 10 mini-libraries nationwide. [Placeholder: add verified locations, dates, number of learners reached, resources distributed, and community outcomes.]"],
  },
  {
    slug: "web3-on-campus",
    title: "Cryptita Plays: Web3 On Campus",
    category: "Campus Education",
    summary: "Campus learning that introduces students to blockchain, Web3, AI, digital literacy, cybersecurity, and related fields.",
    intro: "Web3 On Campus brings emerging-technology education into student communities through seminars, university partnerships, ecosystem sessions, and technical learning.",
    heroImage: images.campus,
    imageAlt: "Students taking part in a classroom learning session",
    why: ["Students benefit from accessible, grounded introductions to technologies that are changing how people build, communicate, and work.", "The program aims to make room for foundational understanding, career exposure, and community-building alongside technical topics."],
    what: ["Topics can include blockchain, Web3, AI, GameFi, DeFi, cybersecurity, digital literacy, and other emerging technologies.", "Program notes list collaborations and sessions involving Marinduque State University, TUP Taguig, UE Manila, UPHS/Biñan, BSU Lipa, NU Lipa, NU Dasmariñas, and other universities and student organizations."],
    impact: ["[Placeholder: add verified event dates, partner-approved names, attendance, learning outcomes, and follow-up activities.]"],
  },
  {
    slug: "builder-programs",
    title: "Cryptita Plays Builder Programs",
    category: "Builder Education",
    summary: "Hands-on pathways that help learners move from technology concepts to building, deploying, and showcasing projects.",
    intro: "Builder Programs turn learning into practice. Participants can work through a pathway from learning fundamentals to building, deploying, and presenting projects.",
    heroImage: images.builders,
    imageAlt: "A group collaborating during a learning activity",
    why: ["Understanding a technology is only one part of learning to use it. Practical projects give learners a chance to apply concepts, encounter real development steps, and explain what they have made.", "The pathway is Learn → Build → Deploy → Showcase."],
    what: ["Activities have included web development, GitHub workflows, smart contracts, blockchain integration, Sui deployment, AI-assisted development, portfolio building, decentralized applications, onchain projects, and builder showcases."],
    impact: ["[Placeholder: add verified cohorts, projects completed, deployment links, learner feedback, and showcase outcomes.]"],
  },
  {
    slug: "builder-highlight",
    title: "Cryptita Plays: Builder Highlight",
    category: "Builder Community",
    summary: "A recurring small-group showcase where emerging builders present projects and participants can try them and share feedback.",
    intro: "Builder Highlight creates a focused setting for emerging builders and projects to meet an audience, demonstrate their work, and hear participant feedback.",
    heroImage: images.community,
    imageAlt: "Community members gathered for a shared activity",
    why: ["Early feedback can help builders understand how people experience a product. A hands-on showcase also gives learners a concrete example of technology in practice."],
    what: ["The first highlighted project was Harvest Protocol, described as an educational programming game where learners use Python to control a farming drone. Participants are encouraged to test the experience, provide feedback, and complete it to receive a Certificate of Participation."],
    impact: ["[Placeholder: add the showcase date, participation details, builder feedback, and any subsequent project milestones.]"],
  },
  {
    slug: "blockchain4youth-collaboration",
    title: "Blockchain4Youth × Cryptita Plays",
    category: "Education Collaboration",
    summary: "A collaboration focused on making blockchain education accessible to young people through campus learning, workshops, resources, and community activities.",
    intro: "Blockchain4Youth × Cryptita Plays brings together education and community activities designed to make blockchain learning more accessible to young people.",
    heroImage: images.event,
    imageAlt: "An educational event setting",
    why: ["Young people need approachable ways to understand blockchain and assess how it may be useful. Learning activities can connect introductory concepts with practical questions and community participation."],
    what: ["The collaboration has supported campus education, builder workshops, educational resources, student activities, Bitcoin Pizza Day, Barya to Blockchain, and community and social-impact initiatives."],
    impact: ["[Placeholder: add partner-approved collaboration timeline, locations, learner reach, resources, and outcomes.]"],
  },
  {
    slug: "blockchain4her-initiatives",
    title: "Blockchain4HER Initiatives",
    category: "Women in Web3",
    summary: "Education and empowerment work supporting greater participation by women in Web3 and emerging technology.",
    intro: "Blockchain4HER Initiatives focus on making space for women to participate, learn, and be recognized across Web3 and emerging technology.",
    heroImage: images.people,
    imageAlt: "A member of the Cryptita Plays community",
    why: ["Broader participation strengthens technology communities. Visibility, learning opportunities, and stories from women in the field can help more people see a place for themselves in the ecosystem."],
    what: ["A major project under this direction is BuildHERs, envisioned as a publication featuring the journeys of women builders, educators, founders, creators, and community leaders."],
    impact: ["[Placeholder: add confirmed activities, publication status, featured contributors, and participation outcomes.]"],
  },
  {
    slug: "barya-to-blockchain",
    title: "Barya to Blockchain",
    category: "Learning Resources",
    summary: "A young learners’ encyclopedia introducing blockchain concepts and digital safety in an approachable format.",
    intro: "Barya to Blockchain: A Young Learners’ Encyclopedia is one of Cryptita Plays’ flagship educational resources, designed to make foundational topics approachable for younger readers.",
    heroImage: images.learning,
    imageAlt: "The cover of an educational resource",
    why: ["Early learning materials can give young readers a starting point for asking informed questions about blockchain and the digital world.", "The encyclopedia also addresses responsible technology use and online safety, alongside technical concepts."],
    what: ["Topics include blockchain, Bitcoin, wallets, smart contracts, NFTs, Web3, digital safety, scam awareness, and responsible technology use. Distribution expanded through the CoinGecko Candy ecosystem."],
    impact: ["The program notes describe thousands of copies as claimed through the CoinGecko Candy ecosystem. [Placeholder: add verified distribution figures, edition details, and reader or educator feedback.]"],
  },
  {
    slug: "cryptita-plays-learning-resources",
    title: "Cryptita Plays Learning Resources",
    category: "Learning Resources",
    summary: "A growing collection of educational materials designed for different ages and stages of learning.",
    intro: "Cryptita Plays Learning Resources extends the education mission beyond a single book, with formats intended to meet learners at different ages and stages.",
    heroImage: images.book,
    imageAlt: "An illustrated educational book cover",
    why: ["Learners encounter new ideas in different ways. A range of accessible materials can support exploration through reading, activities, and classroom learning."],
    what: ["Projects developed or conceptualized include Color Me Crypto, the Web3 Flashcard Box, high-school blockchain modules for Grades 7–10, the Avalanche Student Book, Ada & Blocky children’s stories, BuildHERs, and other beginner-friendly materials."],
    impact: ["[Placeholder: identify which resources are published, in development, or conceptual; add formats, age ranges, distribution, and feedback.]"],
  },
  {
    slug: "ada-and-blocky",
    title: "Ada & Blocky",
    category: "Children’s Education",
    summary: "Stories that introduce children to technology concepts, digital ownership, scams, and online safety.",
    intro: "Ada & Blocky is Cryptita Plays’ storytelling approach to technology education for children, using characters and narratives to make unfamiliar ideas easier to explore.",
    heroImage: images.book,
    imageAlt: "An illustrated educational resource cover",
    why: ["Stories can give younger audiences a friendly context for asking questions about technology and practicing safe choices online."],
    what: ["The stories cover concepts such as blockchain, Bitcoin, smart contracts, tokens, NFTs, scams, digital ownership, and online safety."],
    impact: ["[Placeholder: add story titles, publication status, target ages, distribution plans, and educator or reader feedback.]"],
  },
  {
    slug: "blockchain-ai-education",
    title: "Blockchain × AI Education",
    category: "Emerging Technology",
    summary: "An expanding education direction connecting blockchain, artificial intelligence, digital identity, and practical applications.",
    intro: "As campus programs evolve, Cryptita Plays is extending its education work to include artificial intelligence and the points where AI and blockchain meet.",
    heroImage: images.campus,
    imageAlt: "A classroom technology learning session",
    why: ["Learners need ways to understand emerging tools, consider their limitations, and connect technical ideas to real uses and responsible practice."],
    what: ["Topics include generative AI, AI agents, blockchain and AI integration, AI-assisted coding, prompting and vibe coding, identity and provenance, AI content verification, intelligent decentralized applications, and real-world applications. The upcoming Marinduque State University return program is identified as one program advancing this direction."],
    impact: ["[Placeholder: confirm program date and status; add curriculum, partner details, attendance, and learning outcomes after delivery.]"],
  },
  {
    slug: "train-the-trainers",
    title: "Train-the-Trainers",
    category: "Educator Development",
    summary: "Equipping faculty, educators, student leaders, and community facilitators to continue learning activities beyond an event.",
    intro: "Train-the-Trainers supports a sustainable approach to education by preparing people in universities and communities to carry knowledge forward.",
    heroImage: images.learning,
    imageAlt: "Learning materials prepared for an educational session",
    why: ["A single event has limited reach if knowledge leaves with the organizers. Supporting local educators and facilitators can help learning continue within a community."],
    what: ["The intended participants include faculty members, educators, student leaders, and community facilitators. [Placeholder: add the training format, curriculum, facilitator resources, and eligibility.]"],
    impact: ["[Placeholder: add completed trainings, trained facilitators, follow-on sessions, and participating institutions.]"],
  },
  {
    slug: "campus-builder-career-pathways",
    title: "Campus Builder & Career Pathways",
    category: "Career Pathways",
    summary: "A developing pathway helping students progress from attending events to building, contributing, and exploring technology careers.",
    intro: "Campus Builder & Career Pathways connects learning opportunities with ways students can contribute, develop portfolios, and explore technology work.",
    heroImage: images.builders,
    imageAlt: "Learners collaborating on a project",
    why: ["Students may need support to turn curiosity into practical experience and to understand the range of opportunities available in technology beyond crypto trading."],
    what: ["The pathway is Learner → Builder → Contributor → Innovator. Opportunities may include internships, mentorship, hackathons, ecosystem opportunities, portfolio development, volunteer work, and technology careers."],
    impact: ["[Placeholder: add confirmed pathway stages, partner opportunities, participant examples, and career or contribution outcomes.]"],
  },
  {
    slug: "volunteer-and-ojt-program",
    title: "Volunteer & OJT Program",
    category: "Volunteer Learning",
    summary: "A practical learning environment where students and volunteers can gain experience through real projects and program work.",
    intro: "The Volunteer & OJT Program aims to give students and volunteers opportunities to contribute to real projects while developing practical skills.",
    heroImage: images.community,
    imageAlt: "Community members working together",
    why: ["Applied experience can help learners understand how events, education, and community programs are planned and delivered."],
    what: ["Possible tracks include Community, Events, Creatives, Documentation, Partnerships, Research, Logistics, Programs, Campus Coordination, and Technology. The stated goal is to provide real project experience rather than routine OJT assignments."],
    impact: ["[Placeholder: add application details, available tracks, supervision model, placement duration, and participant work examples.]"],
  },
  {
    slug: "acis-adopt-a-child-iskolar",
    title: "ACIS: Adopt-a-Child Iskolar",
    category: "Scholarship & Student Support",
    summary: "Educational assistance and support for students through the ACIS Scholars initiative and other program-dependent forms of help.",
    intro: "ACIS: Adopt-a-Child Iskolar is the student-support initiative highlighted within Cryptita Plays’ scholarship and educational assistance work.",
    heroImage: images.people,
    imageAlt: "A community member associated with Cryptita Plays",
    why: ["Financial and practical barriers can make it harder for students to continue learning. Educational assistance can help learners access support that fits their circumstances."],
    what: ["Program notes state that three supported ACIS Scholars later graduated. Other support may include learning resources, developer credits, transportation, meals, event access, and assistance depending on the program."],
    impact: ["Three supported scholars are reported to have graduated. [Placeholder: add approved scholar stories, program dates, current eligibility, and verified support details.]"],
  },
  {
    slug: "grantix-social-impact-fundraising",
    title: "GrantiX × Social-Impact Fundraising",
    category: "Social Impact",
    summary: "Using onchain fundraising to support practical educational experiences and community programs.",
    intro: "GrantiX × Social-Impact Fundraising explores how onchain community support can be directed toward learning and social-impact work.",
    heroImage: images.event,
    imageAlt: "A community education event",
    why: ["Fundraising can connect a community’s support to tangible learning opportunities when the use of funds and resulting activities are documented."],
    what: ["The first major use described in the program notes helped fund a hands-on Builders Workshop. The working model is Raise → Educate → Build → Deploy → Document Impact. The next major fundraising direction supports a return to Marinduque."],
    impact: ["[Placeholder: add campaign links, verified amounts, use-of-funds records, workshop details, and documented outcomes.]"],
  },
  {
    slug: "sunday-chain-stories",
    title: "Sunday Chain Stories",
    category: "Community Stories",
    summary: "A content initiative sharing stories of the people who contribute to Web3 communities and social-impact work.",
    intro: "Sunday Chain Stories highlights people whose contributions help Web3 communities function and grow, including those who may receive less public attention.",
    heroImage: images.community,
    imageAlt: "Community members gathered together",
    why: ["Ecosystems are shaped by many kinds of work, not only high-profile roles. Sharing contributors’ experiences can make that work more visible and relatable."],
    what: ["The initiative can feature educators, developers, moderators, volunteers, students, community builders, creators, and social-impact contributors."],
    impact: ["[Placeholder: add published story links, contributor permissions, publication cadence, and audience response.]"],
  },
  {
    slug: "community-ecosystem-collaboration",
    title: "Community & Ecosystem Collaboration",
    category: "Partnerships",
    summary: "Working with ecosystems, universities, communities, and technology organizations to bring learning resources and opportunities closer to learners.",
    intro: "Community & Ecosystem Collaboration brings organizations together around education and access to opportunities, with partnerships intended to support activities rather than serve only as logo placements.",
    heroImage: images.event,
    imageAlt: "Participants at a community education event",
    why: ["Universities, communities, ecosystems, and technology organizations can each contribute relationships, knowledge, resources, or opportunities that support learners."],
    what: ["Program notes name collaborations over the years involving Blockchain4Youth, Blockchain4HER, Avalanche Team1, Base Philippines, Binance Academy, Gate, GrantiX, CoinEx Charity, OKX, MEXC Foundation, LBank Academy, Sui, DEVCON communities, CoinGecko, Bitskwela, and others."],
    impact: ["[Placeholder: confirm partner names and permissions; add collaboration dates, activities, and attributable outcomes.]"],
  },
];

export const initiatives: EditorialStory[] = initiativeRecords.map(({ why, what, impact, bullets, ...story }) => ({
  ...story,
  heroImage: initiativeFeaturedImages[story.slug] ?? story.heroImage,
  gallery: initiativeMedia[story.slug],
  sections: [
    { heading: "Why it matters", paragraphs: why },
    { heading: "What we do", paragraphs: what, ...(bullets ? { bullets } : {}) },
    ...(() => {
      // Keep incomplete editorial prompts out of the public program description.
      const paragraphs = impact.map((text) => text.replace(/\[Placeholder:[^\]]*\]/g, "").trim()).filter(Boolean);
      return paragraphs.length ? [{ heading: "Impact", paragraphs }] : [];
    })(),
  ],
}));

export const initiativeBySlug: Record<string, EditorialStory> = Object.fromEntries(
  initiatives.map((initiative) => [initiative.slug, initiative]),
);

export const sampleStory: EditorialStory = {
  publicationStatus: "draft",
  slug: "what-responsible-web3-education-looks-like",
  title: "What responsible Web3 education looks like",
  category: "Field Notes",
  summary: "Why we start with digital safety, critical thinking, and foundational understanding—not hype.",
  intro: "Responsible Web3 education starts by helping learners understand the basics, ask careful questions, and make informed choices. The goal is useful knowledge, not pressure to adopt a product or make a financial decision.",
  heroImage: initiativeFeaturedImages["web3-on-campus"] ?? images.campus,
  imageAlt: "Students attending a classroom learning session",
  gallery: initiativeMedia["web3-on-campus"],
  sections: [
    {
      heading: "Why it matters",
      paragraphs: [
        "Web3 conversations can move quickly from new technology to big promises. Learners deserve the time and context to understand what a tool does, what it does not do, and what risks may come with using it.",
        "Digital safety and critical thinking make a stronger foundation than hype. [Placeholder: add a verified Cryptita Plays teaching example or participant reflection.]",
      ],
    },
    {
      heading: "What responsible education includes",
      paragraphs: [
        "Start with clear explanations of foundational ideas. Define terms, show how systems work, and make space for questions before moving into more advanced topics.",
        "Discuss digital safety, privacy, scams, and the importance of checking claims. Separate educational demonstrations from investment advice, and make uncertainty visible when a topic is still emerging.",
      ],
      bullets: ["Build foundational understanding before advanced tools", "Practice digital safety and critical evaluation", "Use hands-on learning with clear context", "Make room for questions, limitations, and uncertainty"],
    },
    {
      heading: "Impact",
      paragraphs: [
        "A responsible learning experience should leave participants better equipped to evaluate information and choose their next steps for themselves. [Placeholder: add approved program outcomes, learner feedback, and examples from a completed Cryptita Plays session.]",
        "This article is a sample editorial post based on the existing Field Notes & Events card. The examples and outcomes should be replaced or expanded with verified Cryptita Plays material before publication as a factual report.",
      ],
    },
  ],
  relatedSlugs: ["web3-on-campus", "builder-programs", "blockchain-ai-education"],
};

export const stories: EditorialStory[] = [sampleStory];
