import { createRequestHandler } from "react-router";
import mediaAssets from "../shared/media-assets.json";
import { serveMedia, type MediaAsset } from "./media";

const assetMap: Record<string, MediaAsset> = mediaAssets;

const handleRequest = createRequestHandler(
  // Generated by `npm run build:cloudflare`, bundled by Wrangler.
  // @ts-expect-error The generated server build has no declaration file.
  () => import("../build/server/index.js"),
  "production",
);

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    let response: Response;
    if (env.ENVIRONMENT === "production" && url.hostname === "www.cryptitaplays.com") {
      url.hostname = "cryptitaplays.com";
      url.protocol = "https:";
      response = Response.redirect(url.toString(), 308);
    } else if (url.pathname === "/robots.txt") {
      response = new Response(
        env.ENVIRONMENT === "production" ? "User-agent: *\nAllow: /\n" : "User-agent: *\nDisallow: /\n",
        { headers: { "Content-Type": "text/plain; charset=utf-8" } },
      );
    } else {
      let pathname: string | null;
      try { pathname = decodeURIComponent(url.pathname); }
      catch { pathname = null; }
      if (pathname === null) {
        response = new Response("Invalid URL encoding", { status: 400 });
      } else if (Object.hasOwn(assetMap, pathname)) {
        const asset = assetMap[pathname];
        const cacheable = request.method === "GET" && !["Range", "If-Match", "If-None-Match", "If-Modified-Since", "If-Unmodified-Since"].some(header => request.headers.has(header));
        const cacheKey = new Request(`${env.SITE_ORIGIN}/__r2-cache/${encodeURIComponent(asset.key)}`);
        const mediaCache = cacheable ? await caches.open("cryptita-media") : undefined;
        const cached = await mediaCache?.match(cacheKey);
        response = cached || await serveMedia(request, env.MEDIA, asset);
        if (mediaCache && !cached && response.status === 200) {
          ctx.waitUntil(mediaCache.put(cacheKey, response.clone()).catch(error => {
            console.error("Media cache write failed", error);
          }));
        }
      } else {
        response = await env.ASSETS.fetch(request);
        if (response.status === 404) response = await handleRequest(request);
      }
    }
    const result = new Response(request.method === "HEAD" ? null : response.body, response);
    result.headers.set("X-Content-Type-Options", "nosniff");
    result.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
    if (env.ENVIRONMENT !== "production") {
      result.headers.set("X-Robots-Tag", "noindex, nofollow, noarchive");
    }
    return result;
  },
} satisfies ExportedHandler<Env>;
